# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Chicana por mi Raza Oral History Analysis 
email: marcosv@uidaho.edu
description: CPMR Oral Histories 
date: 2019

#need to change below

# library's domain (only changed if using github pages)
url: https:/marcosvdotcom.github.io
# baseurl: /voices
baseurl: /cpmr
github_username: uidaholib
github_repository: https://github.com/uidaholib/gayrodeo_source

collections:
  transcripts:
      output: true
      permalink: /interviews/:collection/:name
  interviews:
      output: true
      permalink: /:collection/:name

defaults:
  - scope:
      type: transcripts
    values:
      layout: transcript
  - scope:
      type: interviews
    values:
      layout: interviews
      


# Build settings
markdown: kramdown

theme: jekyll-theme-slate